### PR TITLE
Fix PostHTML expression config

### PR DESCRIPTION
**Pull request by Jordinateur**
Hi!

The expression configuration in build.expression, is not merged correctly just before rendering.

In my use case i want te remove locals scripts, and on the V5 nothing is removed.
After some investigation i saw that the merge with the locals key in expression config was not done properly.

I added some test that you can check. Maybe you'll want this test not to be in the component loading test. Tell me if you want me to add a new test.

Thanks for your time once more.

### CODE REVIEW

**Comment by cossssmin** [comment]
Thanks, will have a look tomorrow. Is it ready or still working on it? I see you marked it as a draft. 

Btw I should probably open an issue with known issues that I’ve run into while testing the beta (working on them) just in case so we don’t overlap.

**Comment by Jordinateur** [comment]
I will take a closer look tomorrow on it as well and let you know when I'm done with it.

And yeah do as want for the issue, I don't want to mess things up with your work.

**Comment by cossssmin** [comment]
Had another look and I think it's better to have a separate test and stub for this, yes. 

Otherwise looks good👍

**Comment by cossssmin** [comment]
Went ahead and extracted the test and merged the PR, thanks for catching and fixing this!

**Pull request merged**
