### PR TITLE
Typescript typings

### PR DESCRIPTION
**Pull request by gaurishhs**
From: https://github.com/maizzle/framework/issues/1052

Please suggest changes (if any) 
All this has been taken from the documentation.

### CODE REVIEW

**Comment by cossssmin** [comment]
Thanks! Can we start with fixing the linting issues please? 😇

**Comment by gaurishhs** [comment]
How do you enable intellisense for these issues? I do have the ESLint extension installed

**Comment by cossssmin** [comment]
We’re using XO, you’ll need the linter plugin, here it is for VS Code:

https://github.com/xojs/vscode-linter-xo

**Comment by gaurishhs** [comment]
hi @cossssmin any updates?

**Comment by cossssmin** [comment]
Getting the same error for both imports:

image

And for example `prettify` doesn't show any suggestions:

image

`markdown` is missing from the `Config` interface (it's only defined for the method in the `RenderOptions`, but I can add that no worries.

**Comment by cossssmin** [comment]
Actually on the `markdown` note, if I do this:

```
interface MarkdownConfig {
  root?: string;
  encoding?: string;
  markdownit?: Options;
  plugins?: [];
}
```

Then add it to the `Config` interface:

```
interface Config {
  markdown?: MarkdownConfig;
}
```

... I'm not seeing it autocomplete/suggested when doing Ctrl+Space?

I'm sorry, I have no experience with TS this is all new to me.

**Comment by cossssmin** [comment]
Nevermind, need to import the correct interface, going through it now 👍

```
/** @type {import('@maizzle/framework').Config} */
```

**Comment by gaurishhs** [comment]
yeah, you were importing the whole module instead of the interface. I made sure to have the same interface name as tailwind's.

**Comment by cossssmin** [comment]
Working on adding JSDoc to everything so you can see a short description in the suggestions dropdown or when hovering over a key. What do you think of using `@defaultValue` like this, to let the user know what the default is in Maizzle?

```ts
interface LayoutsConfig {
  /**
   * Name of the fill tag, where the content will be injected.
   * This is typically used in a Template file, to extend a Layout.
   * @defaultValue `'block'`
   */
  fillTagName?: string;
}
```

**Comment by gaurishhs** [comment]
I did that as well but i removed it later, it seemed like a waste of time
to me because I just copied text from docs which the user should read.
That's a great option but imo it's just a waste of time to maintain that
along with the upcoming changes (it adds more work for a developer to get a
release with a lot of changes out fast). Also, it's @default not
@defaultValue https://github.com/microsoft/tsdoc/issues/27

**Comment by cossssmin** [comment]
I really like that you can 'read the docs' right in the editor this way, looks pretty good and I'm OK with added maintenance because it adds value to the user.

image

Also, thanks for the pointer about `@default` 👍

**Comment by cossssmin** [comment]
Made some changes:

- added new types (i.e. for `query-string`)
- created some new intefaces for config types
- added JSDoc so the IDE shows a description and defaults/examples

The file is pretty big now so I'm thinking of splitting it up into multiple files, what do you think? We can release `v4.6.0` as it is now, we can refactor/split it later.

**Comment by gaurishhs** [comment]
Yeah, that seems good.

**Comment by cossssmin** [comment]
Cool, merging and will release `v4.6.0` tomorrow. Thank you for your contribution!

**Pull request merged**
