### PR TITLE
Maizzle v4.0

### LINKED ISSUE #603: Node `render` not picking up maizzle config
- Maizzle Version: 3.7.2
- Node.js Version: 14.7.3

Hi there,

I'm trying to build my templates at runtime with node. I have a function at `src/api/routes/foo/index.js` that uses `Maizzle.render()` with a template. `render()` is picking up my tailwind config at `tailwind.config.js` (including custom colors etc.), but it isn't picking up my maizzle config at `config.js` (or ideally `config.production.js`). I'm having to manually import the right maizzle config depending on the node environment, and pass it as the `maizzle` option in `render()`. 

Surely my config should be picked up automatically? How come the tailwind config is picked up but not the maizzle config? Apologies if i'm missing anything obvious. Thanks!

### LINKED ISSUE #605: Suggestion: Lazy Init Browsersync
- Maizzle Version: 3.7.2
- Node.js Version: 12.22.9

First of all, thank you for putting together a truly remarkable project. 👏 

### Issue
I'm using Maizzle in a NextJS serverless function hosted on their Vercel environment. I'm using the [Node Render](https://maizzle.com/docs/nodejs/) function to dynamically render and send HTML emails. Locally I had no issues, however as soon as I deployed to Vercel's serverless function environment I started getting this error:
```bash
Error: ENOENT: no such file or directory, open '/var/task/curriculum/curriculum/node_modules/browser-sync-ui/lib/plugins/sync-options/sync-options.html'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at fileContent (/var/task/curriculum/curriculum/node_modules/browser-sync-ui/lib/plugins/sync-options/sync-options.plugin.js:65:26)
    at Object.<anonymous> (/var/task/curriculum/curriculum/node_modules/browser-sync-ui/lib/plugins/sync-options/sync-options.plugin.js:45:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/var/task/curriculum/curriculum/node_modules/browser-sync-ui/lib/plugins/sync-options/sync-options.html'
}
```
I was able to confirm that Vercel was somehow pruning these files from the `node_modules` folder. My hypothesis is that it has something to do with [this](https://nextjs.org/docs/advanced-features/output-file-tracing).

After spending some trying and failing to get Vercel to not purge these files, I started to see if I could figure out why Browsersync was trying to run in production in the first place. I was able to track it down to this line: https://github.com/maizzle/framework/blob/a0e41c0ba104f925ceda02192f5bb5f90785638e/src/index.js#L5

To validate this hypothesis, I reproduced the production error locally by deleting the files in `node_modules/browser-sync-ui/lib/plugins/sync-options/` and triggering Maizzle.render. I then made the following patch (this [patched](https://www.npmjs.com/package/patch-package) module is now running fine in production):
```patch
diff --git a/node_modules/@maizzle/framework/src/index.js b/node_modules/@maizzle/framework/src/index.js
index f258852..f87105a 100644
--- a/node_modules/@maizzle/framework/src/index.js
+++ b/node_modules/@maizzle/framework/src/index.js
@@ -2,7 +2,6 @@ const ora = require('ora')
 const path = require('path')
 const fs = require('fs-extra')
 const {get, merge} = require('lodash')
-const bs = require('browser-sync').create()
 const Config = require('./generators/config')
 const Output = require('./generators/output')
 const transformers = require('./transformers')
@@ -10,6 +9,15 @@ const {clearConsole} = require('./utils/helpers')
 const Plaintext = require('./generators/plaintext')
 const Tailwind = require('./generators/tailwindcss')
 
+const getBrowserSync = () => {
+  if(!global.cachedBrowserSync) {
+    const bs = require('browser-sync')
+    global.cachedBrowserSync = bs.create()
+  }
+
+  return global.cachedBrowserSync
+}
+
 const self = module.exports = { // eslint-disable-line
   ...transformers,
   render: async (html, options) => Output.toString(html, options),
@@ -66,7 +74,7 @@ const self = module.exports = { // eslint-disable-line
         const spinner = ora()
 
         // Watch for Template file changes
-        bs.watch(templatePaths)
+        getBrowserSync().watch(templatePaths)
           .on('change', async file => {
             clearConsole()
 
@@ -115,25 +123,25 @@ const self = module.exports = { // eslint-disable-line
               .render(await fs.readFile(file, 'utf8'), renderOptions)
               .then(({html, config}) => fs.outputFile(config.permalink || finalDestination, html))
               .then(() => {
-                bs.reload()
+                getBrowserSync().reload()
                 spinner.succeed(`Compiled in ${(Date.now() - start) / 1000}s [${file}]`)
               })
               .catch(() => spinner.warn(`Received empty HTML, please save your file again [${file}]`))
           })
 
         // Watch for changes in all other files
-        bs.watch(globalPaths, {ignored: templatePaths})
-          .on('change', () => self.build(env, config).then(() => bs.reload()))
-          .on('unlink', () => self.build(env, config).then(() => bs.reload()))
+        getBrowserSync().watch(globalPaths, {ignored: templatePaths})
+          .on('change', () => self.build(env, config).then(() => getBrowserSync().reload()))
+          .on('unlink', () => self.build(env, config).then(() => getBrowserSync().reload()))
 
         // Watch for changes in config files
-        bs.watch('config*.js')
+        getBrowserSync().watch('config*.js')
           .on('change', async file => {
             const parsedEnv = path.parse(file).name.split('.')[1] || 'local'
 
             Config
               .getMerged(parsedEnv)
-              .then(config => self.build(parsedEnv, config).then(() => bs.reload()))
+              .then(config => self.build(parsedEnv, config).then(() => getBrowserSync().reload()))
           })
 
         // Browsersync options
@@ -154,10 +162,11 @@ const self = module.exports = { // eslint-disable-line
         }
 
         // Initialize Browsersync
-        bs.init(bsOptions, () => {})
+        getBrowserSync().init(bsOptions, () => {})
       })
       .catch(error => {
         throw error
       })
   }
 }
+
```

Since this worked, I figured I'd reach out here to get some feedback and see if it's worth throwing up a PR for. 

Thanks again for this awesome project 🙏

### PR DESCRIPTION
**Pull request by cossssmin**
This PR adds new features and fixes a few bugs in Maizzle.

- BREAKING: added support for Tailwind 3.x
- BREAKING: use plaintext config only from template config [7d10325](https://github.com/maizzle/framework/pull/575/commits/7d10325d646c38e22518e3d278d12f8870ac9081), #469 
- BREAKING: refactored the baseImageURL transformer
- FIXED: tailwind css purging when using custom template source paths #545
- FEAT: lazy load Browsersync #605 
- FEAT: allow disabling console clearing #544 
- FEAT: support templates source as function #560 
- FEAT: support defining templates source as array #560 
- FIX: safeClassNames config priority
- FEAT: support `tailwindcss` attribute for transforming with PostCSS
- FEAT: support attributes as locals for components
- FEAT: throw on tailwind compile error
---

fixes #603, closes #605

### CODE REVIEW

**Comment by yellow1912** [comment]
cant wait for this

**Comment by citrus** [comment]
Any status updates here?

**Comment by cossssmin** [comment]
> Any status updates here?

Working on it, aiming at realeasing this month.

https://twitter.com/cossssmin/status/1480268313393516550

**Comment by anlexN** [comment]
when to release it? i need it very much. please!

**Comment by dewey** [comment]
@anlexN you can clearly see he's working on it. Be patient.

**Comment by anlexN** [comment]
the day after tomorrow, I need to do email marketing to my customer. i did review the tailwind docs step by step.
Happy spring festival. every one! Good lucky to you all.

**Comment by cossssmin** [comment]
We should have an alpha ready this coming week 👍

**Review by anlexN — COMMENTED** [review]
now these codes are good idea. thank you to invite me to review chanages.
Because i have no much time to review all code in the maizzle step by step, i am afraid that i can not do my best more.

**Comment by cossssmin** [comment]
> now these codes are good idea. thank you to invite me to review chanages. 

Not sure why that happened, sorry about that!

**Review by anlexN — COMMENTED** [review]
good idea

**Pull request merged**
