### PR TITLE
feat: add config assets array support

### PR DESCRIPTION
**Pull request by obiwan00**
I would like to add support for `Array` to config `templates.assets`. I need to add several assets and build each of them into separate directories.

## Issue Description
In my case, there is an `email-kit` directory with components and images but without templates. I would like to add assets and build each of them into their own directory. I can add `email-kit` assets to some other template config, but there is no option to separate asset destinations for different assets. In this case, adding to config `templates.assets` `Array` support will be helpful.

## Proposed solution
Normalize `assets` to `Array` and handle assets via `for` loop.

## Example
```
// Simplified monorepo directory structure with shared packages for different projects
├───projects
│   ├───project-1
│   │   └───maizzle // <-- config.js
│   │       ├───images // 🖼 assets
│   │       └───templates
│   └───project-2
└───shared-packages
    ├───email-kit
    │   ├───components
    │   └───images // 🖼 assets without own templates
    ├───package-A
    │   ├───images // 🖼 assets
    │   └───templates
    └───package-B // 🖼 assets
```
```
// Shortened expected output result
└───images
    ├───email-kit
    ├───package-A
    ├───package-B
    └───project-1
```
``` js
module.exports = {
  build: {
    templates: [
      {
        source: 'src/templates',
        destination: {
          path: destinationPath,
        },
        assets: [
          {
            source: 'src/images',
            destination: 'images/project-1',
          },
          {
            source: '../../../shared-packages/email-kit/images',
            destination: 'images/email-kit',
          },
        ]
      },
      // ... template config for each package
      {
        source: '../../../shared-packages/package-A/templates',
        destination: `${destinationPath}/package-A`,
        assets: {
          source: '../../../shared-packages/package-A/images',
          destination: 'images/package-A'
        }
      },
      // ...
    ],
    // ...
  }
}
```

Thank you for the great work!

### CODE REVIEW

**Comment by cossssmin** [comment]
Thanks for working on this :)

Can you please add a test to make sure this works as expected? See the current [assets test](https://github.com/maizzle/framework/blob/master/test/test-todisk.js#L217) if you need inspiration.

**Comment by obiwan00** [comment]
Could you check the tests on the master branch? There are 7 tests that fail.

**Comment by cossssmin** [comment]
All tests are passing on `master` right now, do you mean they fail on your end?

**Comment by obiwan00** [comment]
I have 7 tests failed on master branch. One of the faild tests

```
todisk › outputs plaintext files

  test\test-todisk.js:156

   155:
   156:   t.is(                                                             
   157:     await fs.readFile(`${t.context.folder}/plaintext.html`, 'utf8'),

  Difference (- actual, + expected):

  - `<div>Show in HTML</div>␍␊
  - ␍␊
  - ␍␊
  -   <p>Do not show <a href="url">this</a> in plaintext.</p>␍␊
  - ␍␊
  + `<div>Show in HTML</div>␊
  + ␊
  + ␊
  +   <p>Do not show <a href="url">this</a> in plaintext.</p>␊
  + ␊
    `

  › test/test-todisk.js:156:5

  ─

  7 tests failed

```

**Comment by cossssmin** [comment]
They're failing because they've contain a mix of CRLF and LF line endings on your machine. Open each fixture/expect file and save them with LF line endings and run the tests again 👍

**Comment by obiwan00** [comment]
It helps in some cases. But there are still some issues with this. I may ignore those failed tests for now.

**Comment by obiwan00** [comment]
Added tests

**Pull request merged**
