### PR TITLE
Lazy Init broswersync

### PR DESCRIPTION
**Pull request by digitalmaster**
[Issue](https://github.com/maizzle/framework/issues/605)

## Changes
- Only initialize BroswerSync once, when needed 9f6375d6d0f1785c90bc6e022d9de830210a3793

## Rationale
This to avoid unnecessary environment issues when trying to run `Maizzle.render()` in environments that purge unused node modules (ie, Vercel Serverless function environment)

See [issue](https://github.com/maizzle/framework/issues/605) for more details.

## How to Test
Run unit tests and/or give broswersync a spin 

**Expectation:** BrowserSync should continue to work as expected

### CODE REVIEW

**Comment by digitalmaster** [comment]
@cossssmin Would love some eyes on this PR when you have a moment. Let me know if there's anything missing/broken/etc 🙏 

Sidenote: I'm surprised that CI Checks don't run on this branch 🤔 Am I doing something wrong 🙈 😆 ?

**Comment by cossssmin** [comment]
Thanks for the PR, just pulled and ran tests locally - all is good. CI didn't run probably because the repo had "Require approval for first-time contributors" :) It'll run once merged into 4.0 👍

**Comment by cossssmin** [comment]
> Sidenote: I'm surprised that CI Checks don't run on this branch 🤔 Am I doing something wrong 🙈 😆 ?

CI also didn't because of this:

https://github.com/maizzle/framework/blob/a0e41c0ba104f925ceda02192f5bb5f90785638e/.github/workflows/nodejs.yml#L6-L10

Going to update it so that it runs on all PRs 👍

**Comment by digitalmaster** [comment]
Brilliant! This should help a lot. Nice find! 👏 🥳

**Pull request merged**
